import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./(components)/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fajr o' Clock",
  description: "Generated by Humza Qureshi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex flex-col h-screen max-h-screen'>
          <Nav />
          <div className="flex-grow overflow-y-auto bg-slate-600 text-dafault-text">
            {children}
          </div>
        </div>
      </body>

    </html>
  );
}
